export const DETAIL_PHONES_FETCHED = "DETAIL_PHONES_FETCHED";
export const FETCHING_DETAIL_PHONES = "IS_FETCHING_DETAIL_PHONES";
export const FETCHING_DETAIL_PHONES_FAILURE = "FETCHING_DETAIL_PHONES_FAILURE";
